//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeLii.Roadio.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookmark()
        {
            this.POIBookmarks = new HashSet<POIBookmark>();
        }
    
        public int BookmarkId { get; set; }
        public string BookmarkName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POIBookmark> POIBookmarks { get; set; }
    }
}
