//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeLii.Roadio.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POI()
        {
            this.POIBookmarks = new HashSet<POIBookmark>();
            this.POIPhotoes = new HashSet<POIPhoto>();
            this.POITags = new HashSet<POITag>();
        }
    
        public int POIId { get; set; }
        public Nullable<int> POICategoryId { get; set; }
        public string POIName { get; set; }
        public string POIDescription { get; set; }
        public string NearestCity { get; set; }
        public string NearestVillage { get; set; }
        public string NearestStateHighway { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual POICategory POICategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POIBookmark> POIBookmarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POIPhoto> POIPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POITag> POITags { get; set; }
    }
}
