//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeLii.Roadio.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class POIPhoto
    {
        public int POIPhotoId { get; set; }
        public Nullable<int> POIId { get; set; }
        public string PhotoFileName { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
    
        public virtual POI POI { get; set; }
    }
}
