//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeeLii.Roadio.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoadioDatabaseEntities : DbContext
    {
        public RoadioDatabaseEntities()
            : base("name=RoadioDatabaseConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<Contributor> Contributors { get; set; }
        public virtual DbSet<POI> POIs { get; set; }
        public virtual DbSet<POIBookmark> POIBookmarks { get; set; }
        public virtual DbSet<POICategory> POICategories { get; set; }
        public virtual DbSet<POIFeedback> POIFeedbacks { get; set; }
        public virtual DbSet<POIPhoto> POIPhotoes { get; set; }
        public virtual DbSet<POITag> POITags { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
