CREATE TABLE [dbo].[POITag]
(
	[POITagId] INT NOT NULL PRIMARY KEY, 
    [POIId] INT NULL, 
    [TagId] INT NULL, 
    CONSTRAINT [FK_POITag_Tag_TagId] FOREIGN KEY (TagId) REFERENCES [Tag](TagId), 
    CONSTRAINT [FK_POITag_POI_POIId] FOREIGN KEY (POIId) REFERENCES [POI](POIId) 
)
